### ISSUE TITLE
{getaddrinfo-backend}: Servname not supported for ai_socktype

### ISSUE THREAD

**Issue by podstreet** [varnish/docker-hitch#12]
Getting the following error message when trying to start Hitch. And then it dies.

```
{getaddrinfo-backend}: Servname not supported for ai_socktype
```

Full log is:

```
hitch  | 20221130T204837.621243 [    1] {core} hitch 1.7.0 starting
hitch  | 20221130T204837.621458 [    1] {getaddrinfo-backend}: Servname not supported for ai_socktype
```

When trying to start the Hitch container:

docker-compose.yml

```
version: '3'
services:
    varnish:
        image: varnish:fresh
        container_name: varnish
        volumes:
            - "./default.vcl:/etc/varnish/default.vcl"
            - "./letsencrypt.vcl:/etc/varnish/letsencrypt.vcl"
        ports:
            - "80:80"
            - "8443:8443"
        tmpfs:
            - /var/lib/varnish:exec
        environment:
            - VARNISH_SIZE=2G
        command: "-p default_keep=300"
        user: root
        extra_hosts:
            - "host.docker.internal:host-gateway"
    hitch:
      image: "hitch:1.7.0"
      container_name: hitch
      hostname: hitch
      ports:
        - "443:443"
      command: --backend=[varnish]:8443:/etc/letsencrypt/live/domain.com/hitch-bundle.pem --alpn-protos=http/1.1 --write-proxy-v2=off
      depends_on:
        - varnish   
```

I have tested Hitch 1.7.0, 1.7.2, 1.7.3. 

System Details:

```
Docker version 20.10.21, build baeda1f
Ubuntu 20.04
```
